### ISSUE TITLE
UPRN support in services

### ISSUE THREAD

**Issue by peterkwells** [OpenAddressesUK/roadmap#101]
UPRNs are open data: http://www.ordnancesurvey.co.uk/about/news/2015/uprn-release-sharing-location-data.html

Open Addresses gathers and publishes data through a number of methods: as static bulk data, as linked data on the Internet and as a set of APIs that can be used to build digital services. Each of these methods will be expanded to cater for OS UPRNs both when gathering and publishing data.

Expand the Open Address data model, linked URLs and API services to, where appropriate, support open data UPRNs. First step will be to assess where required before dev. Dev may split into multiple tasks.

Note that this feature does not include bulk update of UPRNs. That is https://github.com/OpenAddressesUK/roadmap/issues/106

**Comment by pezholio** [comment]
Need to:
- [ ] Add UPRNs to the data model - both Turbot, Ernest and the main database
- [ ] Add ways for users to add / suggest UPRNs to existing addresses
- [ ] Add search by UPRN functionality

**Comment by peterkwells** [comment]
Blogpost announcing it's done being merged on MOnday https://github.com/OpenAddressesUK/theodolite/pull/207

**Comment by peterkwells** [comment]
@pezholio ok to close this one?

**Comment by pezholio** [comment]
Yup, I reckon so :smiley_cat:

**Comment by peterkwells** [comment]
Job done :ballot_box_with_check:
