### ISSUE TITLE
"Pure JavaScript ETL" (PJSETL)

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#16]
Depends on:
- https://github.com/OpenAddressesUK/roadmap/issues/52
- https://github.com/OpenAddressesUK/roadmap/issues/15

This is a lightweight, pure JavaScript implementation of an ETL for the ingestion of individual addresses, running in the web browser and suitable for non-intrusive third party integration. 

By integrating the PJSETL, a partner website submits to OA every address being input by their users on their website. The submission is a side-effect to some other pre-existing process, e.g. ordering a pizza for delivery.  

The PJSETL also offers services back to the hosting page, e.g. the normalisation of the address using our https://github.com/OpenAddressesUK/roadmap/issues/15 and possibly its validation by querying the publishing APIs.

This should be designed to be complementary to https://github.com/OpenAddressesUK/roadmap/issues/35 . The two components together should be able to cover a typical, **basic** journey by which a user:
- searches for her address by inputting her postcode and selecting among a possible list of house numbers and names
- if the address cannot be found, she can write it from scratch
- the address components are matched vs our reference tables and presented back to her for confirmation
- on confirmation, the address is both handed over to the hosting website and to OA for confirmation / ingestion

**Comment by Floppy** [comment]
This is now done. Remaining work on that user journey is in #35.
