### ISSUE TITLE
Common ETL - Integration of ONS' "Index of Place Names" for the localities reference table

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#19]
See also https://github.com/OpenAddressesUK/roadmap/issues/15 .

**Comment by peterkwells** [comment]
Another candidate for use in Common ETL has been suggested here:

https://trello.com/c/IjLnOGDe/30-usg-nuclear-targetting-database

**Comment by peterkwells** [comment]
Closing. This will get picked up int he work around OS Open Names.
