### ISSUE TITLE
Write new ETL from open data / public domain datasets

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#21]
Depends on everything defined in:
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/1
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/2
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/3
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/4
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/5 
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/7
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/8
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/10
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/11 
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/15
- [ ] https://github.com/OpenAddressesUK/roadmap/issues/20

Candidates:
- [NROSH](http://data.gov.uk/dataset/national-register-of-social-housing-nrosh)
- [Geolytix supermarket data](http://geolytix.co.uk/blog/?p=238)

**Comment by peterkwells** [comment]
Closing as duplicate. There is a seperate issue for loading Spend Networks contribution.
