### ISSUE TITLE
Data take down and quarantine features

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#25]
Make it easy for anyone in OA, without requiring technical skills, to take action following notification of data being 'polluted' by IP. This includes:
- putting the impacted data in 'quarantine' / logical deletion, allowing for its recovery at a later time
- 'park' somewhere not public the past downloadable editions of the data that included the quarantined addresses (note how this implies it is relatively easy for us to tell!)
- publish a list of the deprecated downloadable editions, with accompanying text stating that they contain data which has since been placed in quarantine and should not be used

Note the assumptions that:
- the publishing API will only give access to the latest distillation, so there is no need to take action on that front, too

**Comment by peterkwells** [comment]
Manual process accepted for sprint 40

**Comment by giacecco** [comment]
Ok, automation postponed to https://github.com/OpenAddressesUK/roadmap/issues/62 .

Manual process and terms to be defined at https://github.com/theodi/shared/issues/507 .
