### ISSUE TITLE
Enhancements to the search API (part 1/2)

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#28]
We incredibly missed this for Alpha. The search APIs should support partial string matching. The search functionality of the website at http://alpha.openaddressesuk.org/addresses should be changed accordingly.

**Comment by pezholio** [comment]
Is this a whole address string, or for separate address parts? We could just do a dumb LIKE match, or we could be smarter and use Elasticsearch (we're thinking about using this for the free text addresses ETL anyway)

**Comment by giacecco** [comment]
We need to think to this from a use case point of view first, from both an API and interactive point of view.

Website users / API developers will likely:

a) use partial spellings, e.g. "st james" or "st james sq" instead of "st james square"
b) use alternative spellings and punctuation, e.g. "saint james" or "st. james" instead of "st james", any capitalisation and and any number of spaces, e.g. between the two parts of the postcode
c) use wrong spellings / mistypes, e.g. "st hames" instead of "st james"
d) put content in the wrong field / form textbox (e.g. the postcode in the "town or city" field)
e) do all of the above together!

... in all the API fields / textboxes of the website.

I would like the search APIs and website results to be smart with all scenarios above. If time and budget are not sufficient, I would tackle them in the same order as I described.

I'm including the API developers in this because we can't take for granted they will use our APIs to "normalise" the search request before submitting it to us (e.g. check their town names vs our reference tables).

@peterkwells am I missing anything?

_Then_ we talk about implementation. The volume of data we are dealing - and our inevitable success :-) - suggests we are careful in choosing our tools, particularly if we pay per use. I am happy to use Elasticsearch for example, but before choosing to use it please work with me in defining a model to forecast costs.

At API level in particular, this subject hooks also into https://github.com/OpenAddressesUK/roadmap/issues/58 . E.g. the need to throttle some of the services to assure we can provide them for free.

**Comment by peterkwells** [comment]
Looks a good list

We can expect that more needs will emerge as users start to look at these issues but one in my own head is that we should also be thinking that some people will choose to search for specific addresses and others will choose to search wider, e.g. I might deliberately want to search for "Camberwell" out of curiousity; to see if it exists; to understand coverage; or as part of an integration case to support use cases on an external website.

**Comment by giacecco** [comment]
The example you make about Camberwell is a good point. I believe that at the moment we return results from _addresses_ and not from the reference tables. E.g. we may know that Clifton Street exists from the reference table, but return no results when searching if we don't have at least one address associated to it. This may be worth changing, too. @pezholio can you remind me if what I wrote is correct please?

**Comment by giacecco** [comment]
The opportunity to bring the (a) use case back onto sprint #40 is being evaluated, awaiting for @giacecco and @peterkwells to talk about it.

**Comment by giacecco** [comment]
See https://github.com/theodi/shared/issues/508 .
