### ISSUE TITLE
Better contibution/submission guidelines

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#79]
From @peterkwells' original at https://github.com/OpenAddressesUK/sorting_office/issues/9 .

> We need to tighten up the text on --contribute to align with the text in the Submission Guidelines on the front page.
> 
> Possibly we should have this text mastered on its own so that it can iterate on its own and be included/linked from anywhere that needs it. We are currently planning to add a stronger link to the new take down policy from the frontpage text either Thu or Fri.
> 
> --current frontpage text--
> We do not want to receive any names in the submission, other than any company name that may form part of the address. The Open Addresses data that we publish will be about locations, not about people.
> 
> Do not worry about the format of the address. The platform is designed and built to support many different formats.
> 
> Please be sure not to violate others' intellectual property or privacy rights with your submission. If you think your Intellectual Property rights are being infringed then please email us describing the data that you believe is affected.
> 
> When you submit an address we will capture some additional information: specifically the IP address that you are currently using. This information is used to track submissions and as part of our processes to track provenance and to remove any data that is unlawful. Find out more about our privacy policy.
> 
> By submitting an address you are saying that Open Addresses Limited can re-use the address and publish it under an open data licence. You are saying that the publication of the address by Open Addresses Limited or third parties does not and will not infringe any of your legal rights or those of any third party.
> ----end current frontpage text----

**Comment by peterkwells** [comment]
I've put a PR with a quick hack here: https://github.com/OpenAddressesUK/sorting_office/pull/15 to solve the immediate issue whilst a better solution is found for having duplicated copies of the submission guidelines around the place.

It is meant to simply put the text from the front-screen at the bottom of the page with a link from the bit discussing the contribute flag.

@giacecco can you check if the PR is right and merge it if so? This issue can then stay open for the real thing.

**Comment by peterkwells** [comment]
The longer-term solution also needs to cater for Turbot and probably for keys for the APIs too.

This could take the form of user acceptance during the registration process for these services or it might need something a little more sophisticated. For example, what if the guidelines change or if a single user needs to take a different decision for different datasets.

In the meantime Turbot will take the same short-term solution as Sorting Office with a simple piece of static text.

**Comment by giacecco** [comment]
Now scheduled for the ongoing sprint [here](https://github.com/theodi/shared/issues/548).
