### ISSUE TITLE
Replace OSM when visualising maps

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#83]
... to fully avoid any risk of someone considering user activity on the website as 'derived work' from the observation of the map, e.g. the interactive validation functions. See also https://github.com/OpenAddressesUK/theodolite/issues/104 .

**Comment by peterkwells** [comment]
Following up on discussion in demo meet. Owen Boswarva suggested using Google aerial stuff and thought no derived data risk: https://twitter.com/owenboswarva/status/568411068248272896

Blogpost here where Geolytix say they used Google Maps inc streetview to capture supermarkets: http://geolytix.co.uk/blog/?p=238

I can take an action to check on this with Geolytix and Google

**Comment by giacecco** [comment]
After the demo, we decided to attempt implementing OS OpenSpace, with hiding the map as fallback.

**Comment by systemed** [comment]
In case you're not aware, there are EPSG:3857-format OS StreetView tiles at http://os.openstreetmap.org/

Google's [Ts & Cs](https://developers.google.com/maps/terms) expressly prohibit using their aerial imagery: "You must not use the Service in a manner that gives you or any other person access to mass downloads or bulk feeds of any Content, including but not limited to numerical latitude or longitude coordinates"

**Comment by peterkwells** [comment]
Thanks @systemed. OS Street View is going up shortly:

https://github.com/OpenAddressesUK/theodolite/pull/112

FYI @floppy re OS StreetView sourcing

**Comment by peterkwells** [comment]
I said StreetView, I meant OpenSpace...

**Comment by peterkwells** [comment]
This is done
