### ISSUE TITLE
Tools to learn from user behaviour

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/roadmap#89]
At the moment of writing we do not have tools that allow us to learn from our users use the website and the services in particular. This is beyond conventional analytics as user behaviour analysis can give us quite precise directions on what our users need or would like to use our services for, or on the quality (or lack thereof) of our software. 

We should be able to answer easily to questions such as:
- how many addresses we ingested since yesterday?
- how many failed? what are they?
- what are the most common searches that produce little or no results?

It is not just for internal use, lots could be used externally, too.

See also [here](https://github.com/OpenAddressesUK/roadmap/issues/88) as the two activities are likely to go together.

**Comment by giacecco** [comment]
@peterkwells @patricejb please complete the bullet point list above as the conversation around the new website develops and what it needs.

**Comment by peterkwells** [comment]
See also https://github.com/OpenAddressesUK/roadmap/issues/61

**Comment by peterkwells** [comment]
Closing this issue as too imprecise. There are multiple features already open for service monitoring, analytics and dashboards.

It is more of a design principle for OA that we need to learn from the data and behaviour that we see.
